---
grails:
    profile: web
    codegen:
        defaultPackage: blueloop
    spring:
        transactionManagement:
            proxies: false
    gorm:
        # Whether to autowire entities. 
        # Disabled by default for performance reasons.
        autowire: false         
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true



server:
    contextPath: /blueloop

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
                
    plugin:
        springsecurity: 
            password:
                algorithm: bcrypt
            logout:
                postOnly: false
            rememberMe: 
                createSessionOnSuccess: true
            userLookup:
                userDomainClassName: cr.sa.bl.User
                authorityJoinClassName: cr.sa.bl.UserRole
            authority:
                className: cr.sa.bl.Role
            controllerAnnotations:
                staticRules: [
                        '/':                              ['permitAll'],
                        '/index':                         ['permitAll'],
                        '/monitoring':                    ['permitAll'],
                        '/index.gsp':                     ['permitAll'],
                        '/**/js/**':                      ['permitAll'],
                        '/**/css/**':                     ['permitAll'],
                        '/**/images/**':                  ['permitAll'],
                        '/**/favicon.ico':                ['permitAll'],
                        '/services/**':                   ['permitAll'],
                        '/**/crumb/**':                   ['permitAll'],
                        '/**/city/**':                    ['permitAll'],
                        '/assets/**':                     ['permitAll'],
                        '/**/fonts/**':                   ['permitAll'],
                        '/**/repos/**':                   ['permitAll'],
                        '/**/js_i18n/**':                 ['permitAll']
                    ]
            useSecurityEventListener: true
            failureHandler:
                exceptionMappings: [
                    'org.springframework.security.authentication.CredentialsExpiredException': '/user/passwordExpired'
                    ]

bruteforcedefender:
    time: 5
    allowedNumberOfAttempts: 3

recaptcha:
    publicKey: 6LdQRBcTAAAAAI_YNhUJ28qS9MhMfeWYyLNSITEQ
    privateKey: 6LdQRBcTAAAAAKo37VToFFzRYT8Nu44InaJdJunc
    includeNoScript: true
    includeScript: true
    enabled: true

endpoints:
    jmx:
        unique-names: true

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
        singleSession: true
        flush.mode: manual
    
dataSource:
    pooled: true
    jmxExport: true
    driverClassName: com.mysql.jdbc.Driver
    username: sa
    password:
           
environments:
    development:
        dataSource:
            dbCreate: none
            url: jdbc:mysql://localhost/blueloop?useUnicode=true&characterEncoding=utf-8
            username: root
            password: root
        imageUpload:
            root: /blueloop-backend/
            templateFolderRoute: web-app/templates/
            imagesFolderRoute: web-app/images/
            bbFolderRoute: web-app/images/buildingBlocks/
            canvasFolderRoute: web-app/images/canvas/
            activityFolderRoute: web-app/images/activities/
            riskFolderRoute: web-app/images/risks/
            externalFolderRoute: /blueloop-backend/repos/
            internalFolderRoute: /blueloop-backend/static/
            csv: web-app/csv/
            activitiesURL: /blueloop-backend/static/images/activities/
        aws:
            endpoint: https://s3-us-west-1.amazonaws.com/
            bucketBlAppUsers: blapp-users
            bucketBlAppAssets: blapp-assets
        pubnub:
            channel_name: BlueloopRealtimeDev
    test:
        dataSource:
            dbCreate: none
            url: jdbc:mysql://localhost/blueloop?useUnicode=true&characterEncoding=utf-8
            username: root
            password: root
        imageUpload:
            root: /blueloop-backend/
            templateFolderRoute: web-app/templates/
            imagesFolderRoute: web-app/images/
            bbFolderRoute: web-app/images/buildingBlocks/
            canvasFolderRoute: web-app/images/canvas/
            activityFolderRoute: web-app/images/activities/
            riskFolderRoute: web-app/images/risks/
            externalFolderRoute: /blueloop-backend/repos/
            internalFolderRoute: /blueloop-backend/static/
            csv: web-app/csv/
            activitiesURL: /blueloop-backend/static/images/activities/
        aws:
            endpoint: https://s3-us-west-1.amazonaws.com/
            bucketBlAppUsers: blapp-users
            bucketBlAppAssets: blapp-assets
        pubnub:
            channel_name: BlueloopRealtimeTest
    production:
        dataSource:
            dbCreate: none
            url: jdbc:mysql://bl-primary.clny1y6ajyp4.us-west-1.rds.amazonaws.com:3306/blueloop?useUnicode=true&characterEncoding=utf-8
            username: blprduser
            password: bl2015dbprd
            properties:
                maxActive: 100
                minIdle: 5
                maxIdle: 25
                initialSize: 5
                maxWait: 10000
                maxAge: 10 * 60000
                minEvictableIdleTimeMillis: 60000
                timeBetweenEvictionRunsMillis: 5000
        imageUpload:
            root: /blueloop-backend/           
            repositoryRoute: /home/bitnami/repos/
            templateFolderRoute: /opt/bitnami/apache-tomcat/webapps/blueloop-backend/templates/
            imagesFolderRoute: /opt/bitnami/apache-tomcat/webapps/blueloop-backend/images/
            bbFolderRoute: /opt/bitnami/apache-tomcat/webapps/blueloop-backend/images/buildingBlocks/
            canvasFolderRoute: /opt/bitnami/apache-tomcat/webapps/blueloop-backend/images/canvas/
            activityFolderRoute: /opt/bitnami/apache-tomcat/webapps/blueloop-backend/images/activities/
            riskFolderRoute: /opt/bitnami/apache-tomcat/webapps/blueloop-backend/images/risks/
            csv: /opt/bitnami/apache-tomcat/webapps/blueloop-backend/csv/
            externalFolderRoute: /blueloop-backend/repos/
            internalFolderRoute: /blueloop-backend/static/
            activitiesURL: /blueloop-backend/static/images/activities/
        aws:
            endpoint: https://s3-us-west-1.amazonaws.com/
            bucketBlAppUsers: blapp-users
            bucketBlAppAssets: blapp-assets
        pubnub:
            channel_name: BlueloopRealtimePrd